# Use the official Python image for Python 3.10
FROM python:3.10

# Set the working directory in the container
WORKDIR /app

# Copy the requirements.txt file into the container at /app
COPY requirements.txt /app/

# Install the required Python packages
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port your Flask app will run on (change as needed)
EXPOSE 5000

# Copy your Flask application code into the container
COPY . /app

# Define the command to run your Flask application
CMD ["python", "app.py"]
